### ISSUE TITLE
Route `POST /api/loan/:loan_id/borrowed`

### ISSUE THREAD

**Issue by NathanPERIER** [Le-Fronce-oui/bookshare#41]
## User not logged in

`401 NOT AUTHENTICATED`

## Loan doesn't exist

`404 NOT FOUND`

## User logged in but not as the owner or borrower in the loan

`404 NOT FOUND`

## User logged in as the borrower

`403 NOT AUTHORIZED`

## Loan not accepted yet / declined / already borrowed

`400 BAD REQUEST`

## User logged in as the owner

`200 OK`

**Comment by TristanDevin** [comment]
if logged in as borrower not authorized ?

**Comment by NathanPERIER** [comment]
Yes, only the owner can do this (but it could be the other way around I guess...)
